name: Build Plugin
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Plugin Files
        run: gradle build --no-daemon
          
      - name: Upload Finished Jar
        uses: actions/upload-artifact@v4
        with:
          name: RayTraceAntiXray-Jar
          path: build/libs/*.jar
